export type ClientRosterItem = {
  id: string;
  companyName: string;
  contactName: string;
  sector: string;
  accountManager: string;
  plan: string;
  status: 'active' | 'review' | 'pending';
  note: string;
  nextStep: string;
  lastUpdate: string;
  progress: number;
  identity: string;
  pillar: string;
  objective: string;
  visual: string;
  channels: string[];
};

export const clientRoster: ClientRosterItem[] = [
  {
    id: 'cli_dicolseg',
    companyName: 'DICOLSEG LTDA',
    contactName: 'Equipo directivo',
    sector: 'Tecnologia de Seguridad y Sistemas de Control',
    accountManager: 'Pendiente de asignar',
    plan: 'H1 2026',
    status: 'pending',
    note: 'Control absoluto, reduccion de riesgo y paz mental para operaciones corporativas.',
    nextStep: 'Definir paquete B2B, mantenimiento y alcance comercial.',
    lastUpdate: 'Onboarding',
    progress: 34,
    identity: 'El Titan Corporativo',
    pillar: 'EL HACER',
    objective: 'Leads B2B altamente cualificados y contratos de mantenimiento a largo plazo',
    visual: 'Azules de alto contraste, negros profundos y planos de infraestructura.',
    channels: ['LinkedIn', 'X', 'YouTube'],
  },
  {
    id: 'cli_avila_internacional',
    companyName: 'Jose Avila / Avila Internacional',
    contactName: 'Jose Avila',
    sector: 'Mentoria High-Ticket y Liderazgo Global',
    accountManager: 'Pendiente de asignar',
    plan: 'H1 2026',
    status: 'review',
    note: 'Construccion de autoridad, pertenencia aspiracional y narrativa de liderazgo.',
    nextStep: 'Alinear THE SUMMIT y roadmap de mentorias post-evento.',
    lastUpdate: 'Onboarding',
    progress: 46,
    identity: 'El Arquitecto del Legado',
    pillar: 'Integracion Total',
    objective: 'Sold out de THE SUMMIT y apertura de plazas para mentorias High-Ticket post-evento',
    visual: 'Estetica documental premium con validacion de lifestyle.',
    channels: ['Instagram', 'YouTube', 'TikTok', 'X'],
  },
  {
    id: 'cli_adriana_ortega',
    companyName: 'Dra. Adriana Ortega',
    contactName: 'Dra. Adriana Ortega',
    sector: 'Medicina Alternativa, Funcional e Integral',
    accountManager: 'Pendiente de asignar',
    plan: 'H1 2026',
    status: 'pending',
    note: 'Posicionamiento clinico estricto con profundidad cientifica y confianza.',
    nextStep: 'Definir agenda de consultas privadas y pilares de contenido educativo.',
    lastUpdate: 'Onboarding',
    progress: 41,
    identity: 'La Ciencia del Origen',
    pillar: 'EL SER',
    objective: 'Llenado de agenda de consultas privadas de alto valor',
    visual: 'Luz natural difusa, espacios limpios y cercania paciente-especialista.',
    channels: ['YouTube', 'Instagram'],
  },
  {
    id: 'cli_lucy_moreno',
    companyName: 'Lucy Moreno',
    contactName: 'Lucy Moreno',
    sector: 'Coaching de Marca Personal (Nicho Femenino)',
    accountManager: 'Pendiente de asignar',
    plan: 'H1 2026',
    status: 'review',
    note: 'Escalamiento con equilibrio mental para mujeres líderes del ecosistema wellness.',
    nextStep: 'Diseñar auditorias rapidas y funnel de consultoria 1:1.',
    lastUpdate: 'Onboarding',
    progress: 52,
    identity: 'La Estratega del Bienestar',
    pillar: 'EL HACER + EL SER',
    objective: 'Conversion a programas grupales y consultoria 1:1 High-Ticket',
    visual: 'Cálida pero corporativa, con movimiento, acción y claridad mental.',
    channels: ['LinkedIn', 'Instagram'],
  },
  {
    id: 'cli_star_light_garden',
    companyName: 'Star Light Garden',
    contactName: 'Eva Rosa Zamora',
    sector: 'Fundacion, Neurodiversidad e Inclusion',
    accountManager: 'Pendiente de asignar',
    plan: 'H1 2026',
    status: 'pending',
    note: 'Narrativa de genialidad, potencial y responsabilidad social corporativa.',
    nextStep: 'Alinear documental corto, financiamiento y red de voluntarios.',
    lastUpdate: 'Onboarding',
    progress: 37,
    identity: 'La Arquitecta de la Consciencia',
    pillar: 'EL TENER',
    objective: 'Captacion de fondos, padrinos corporativos y expansion de voluntarios',
    visual: 'Documental puro con correccion naturalista y momentos reales.',
    channels: ['YouTube', 'LinkedIn'],
  },
  {
    id: 'cli_juan_marulanda',
    companyName: 'Dr. Juan Marulanda',
    contactName: 'Dr. Juan Marulanda',
    sector: 'Practica Medica y Soluciones Clinicas',
    accountManager: 'Pendiente de asignar',
    plan: 'H1 2026',
    status: 'review',
    note: 'Autoridad cientifica y seguridad enfocada en diagnostico preciso y seguimiento.',
    nextStep: 'Definir SEO local y guion Doctor Responde para Reels/TikTok.',
    lastUpdate: 'Onboarding',
    progress: 48,
    identity: 'El Criterio Clinico',
    pillar: 'EL SER',
    objective: 'Mas pacientes nuevos y mayor retencion en tratamientos prolongados',
    visual: 'Asepsia, simetria y planos a la altura de los ojos.',
    channels: ['SEO', 'TikTok', 'Reels'],
  },
  {
    id: 'cli_fiesta_auto_insurance',
    companyName: 'Fiesta Auto Insurance',
    contactName: 'Equipo comercial',
    sector: 'Red Regional de Seguros',
    accountManager: 'Pendiente de asignar',
    plan: 'H1 2026',
    status: 'pending',
    note: 'Mensaje directo, resolutivo y agresivo para captacion masiva.',
    nextStep: 'Configurar pruebas A/B de ganchos y creatividades de respuesta rapida.',
    lastUpdate: 'Onboarding',
    progress: 33,
    identity: 'La Maquina de Conversion',
    pillar: 'EL HACER',
    objective: 'Adquisicion masiva de polizas, reduccion del CPA y dominio local',
    visual: 'Dinamismo extremo, colores saturados y retencion inmediata.',
    channels: ['Meta Ads', 'TikTok Ads', 'Instagram'],
  },
  {
    id: 'cli_seguros_diterich',
    companyName: 'Seguros Diterich',
    contactName: 'Direccion comercial',
    sector: 'Empresa Colombiana de Seguros',
    accountManager: 'Pendiente de asignar',
    plan: 'H1 2026',
    status: 'review',
    note: 'Proteccion patrimonial, continuidad empresarial y futuro familiar.',
    nextStep: 'Desarrollar comunicacion High-Ticket para directivos y carteras corporativas.',
    lastUpdate: 'Onboarding',
    progress: 44,
    identity: 'El Escudo Patrimonial',
    pillar: 'EL HACER + EL TENER',
    objective: 'Posicionamiento premium y captacion de carteras corporativas',
    visual: 'Solidez, calidez y enfoque empresarial con tomas estables.',
    channels: ['LinkedIn', 'YouTube', 'Instagram'],
  },
];
